name: KiraEssentialz
version: '1.0'
main: me.kirar00t.kiraessentialz.KiraEssentialz
api-version: '1.20'
authors: [KiraR00t]
description: My first plugin with many QOL features
website: https://www.kirar00t.site/
commands:
  Sethome:
    description: Set your home base
    usage: /<command>
  Home:
    description: Go to your home base
    usage: /<command>
  Clearhome:
    description: Clear current home location
    usage: /<command>
  Show:
    description: Show off your cool enchanted item
    usage: /<command>
  Lastdeath:
    description: Get coordinates of your last death place
    usage: /<command>
  Echest:
    description: Open your enderchest from any place
    usage: /<command>
  TPA:
    description: Send a teleport request to any player
    usage: /<command> <player>
  TPAccept:
    description: Accept pending player request
    usage: /<command>
  OpMenu:
    description: Access menu for operators
    usage: /<command>
  DisablePlugin:
    description: Disable any server plugin
    usage: /<command> <pluginName>
  EnablePlugin:
    description: Enable any server plugin
    usage: /<command> <pluginName>
  Announce:
    description: Send a server wide announcement
    usage: /<command> <message>
  GiveAdminStick:
    description: Get access to funny admin sticc
    usage: /<command> <message>