name: KiraEssentialz
version: '1.0'
main: me.kirar00t.kiraessentialz.KiraEssentialz
api-version: '1.20'
authors: [KiraR00t]
description: My first plugin with many QOL features
website: https://www.kirar00t.site/
commands:
  Sethome:
    description: Set your home base
    usage: /<command>
  Home:
    description: Go to your home base
    usage: /<command>
  Clearhome:
    description: Clear current home location
    usage: /<command>